import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-orange-500 ${inter.className}`}>
        <main className="min-h-[100dvh] flex w-full p-2 pt-8 md:p-8 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
